---
- hosts: kubemaster
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars_files:
  - env_variables 
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --control-plane-endpoint=kubeplane.localdomain --pod-network-cidr=10.10.0.0/16 --cri-socket=unix:///run/containerd/containerd.sock
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml

