---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars_files:
  - env_variables
  tasks:
    - name: create containerd configuration file
      file:
        path: "/etc/modules-load.d/containerd.conf"
        state: touch

    - name: set up containerd prerequisites
      blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
          overlay
          br_netfilter

    - name: load modules
      shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

    - name: create the sysctl params configuration file
      file:
        path: "/etc/sysctl.d/k8s.conf"
        state: touch

    - name: set up containerd networking
      blockinfile:
        path: "/etc/sysctl.d/k8s.conf"
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
          
    - name: Disabling Swap on all nodes
      shell: swapoff -a

    - name: verify the SWAP is off
      command: free -m

    - name: Commenting Swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '(.*swap*)'
        replace: '#\1'

  
