---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars_files:
    - env_variables
  tasks:
    - name: add docker repository
      shell: |
        sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo dnf makecache
        sudo dnf install -y containerd.io
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo systemctl enable --now containerd
        sudo systemctl is-enabled containerd
        sudo systemctl restart containerd

    - name: Find and replace "SystemdCgroup = false" to "SystemdCgroup = true"
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup\s*=\s*false'
        replace: 'SystemdCgroup = true'

    - name: Creating a repository file for Kubernetes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch

    - name: Adding repository details in Kubernetes repo file.
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
          https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Installing required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Starting and Enabling the required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
